/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gaming_headphone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/gaming_headphone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.124, 0.182, -0.088]} rotation={[1.519, -0.321, 1.822]} scale={0.008}>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-0.017, 0.339, -0.175]} rotation={[0.346, 0, -Math.PI]} scale={0.261} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} position={[-0.005, 0.124, -0.071]} rotation={[1.519, -0.321, 1.822]} scale={0.008} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.006']} position={[-0.006, 0.142, -0.071]} rotation={[-1.593, -0.538, -Math.PI / 2]} scale={0.053} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.004']} position={[-0.006, 0.142, -0.071]} rotation={[-1.593, -0.538, -Math.PI / 2]} scale={0.053} />
    </group>
  )
}

useGLTF.preload('/models/gaming_headphone.glb')
